sudo: required

language: bash

services:
  - docker

before_install:
  - docker-compose -v
  - docker-compose build
  - docker-compose run wait5
  - docker-compose run app5
  - docker-compose rm -s -f -v
  - docker-compose run wait8
  - docker-compose run app8  

script:
  - docker pull quay.io/keboola/developer-portal-cli-v2:latest
  - export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository keboola keboola.ex-db-mysql`
  - docker tag keboola/ex-db-mysql:latest $REPOSITORY:master
  - eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login keboola keboola.ex-db-mysql)
  - docker push $REPOSITORY:master
  # Run live test job on new master image
  - docker pull quay.io/keboola/syrup-cli:latest
  - travis_wait docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-mysql 287537333 master
  - travis_wait 30 docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-mysql 287589303 master
  - travis_wait docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-mysql 288410371 master
  - travis_wait docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-mysql 313935368 master

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true

notifications:
  email: false
  slack:
    secure: Q1X3jkeyaagPDuf0rNjtitTV8iYrquIUZ8jhvyvtU8fkydHeN1ovzmvOhagDjCY+nLP2lA4DfcWuChzRyYIgwT95ObEuawtPBg6XxcihFqvjINAHk9nZAgtzpFeWHjxFBx5nxizCUIG+4rsMCgvgwl29RC5O5FnhnkIRY2RNi670tHxBTr5XLPsHoB5SamKTmF2dH+CeFdYWGrGpsPOdt281mjWyBEuTfGFYt0Vf1jNLTL/uGai5LiyE/W+VWOwpPZImPyF6AMS8u8yW5ADmDJ8jc1C8OvwuFfrlv/2njCzMOg2855JqGUQVikyAJ0MyqSMLqZo8WDaVknJf8EtPqOirRVZwSIKK4zVnRIWZsaeM0GlCq6gIq33nySBu9f/JgiyxxexliHEjoPZGBgel1aGFgnFWvkp+9q4XcnRgxG9fyWRXxscFn5OjQXV9gyX5NpMS7hMzkWXXSojfKiZtKV2vJ8CqwqxO11rJSpDANqgh7iqEUeIzfU8TNFEZz3MzbAgGNokD+bpNrTkTxbwGYMcqQggp3DYa3pd6aWNalSrVFEPgil14AtFmu/6ByCIDeEVMW/DDfEKb7Mni4+f66xa0Qw2ajxjHCkULGsVZakWIBViyFzEbgOjo06pHL+Qc+qtEHVa/CttW+zOENri2CPkvABJuwLTyuqtKOUcodTo=
