version: "3"
services:
  app: &app
    build: .
    image: keboola/db-extractor-mysql
    command: composer ci
    environment:
      KBC_COMPONENT_RUN_MODE: run
      MYSQL_DB_HOST: mysql
      MYSQL_DB_SSL_HOST: mysql-ssl
      MYSQL_DB_SSL_BAD_CN_HOST: mysql-different-cn
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: rootpassword
      MYSQL_DB_DATABASE: test
      MYSQL_DB_PORT: 3306
    volumes:
      - ./docker/ssl/certificates:/ssl-cert
      - ssh-keys:/root/.ssh:ro
    links:
      - mysql
      - mysql-ssl
      - mysql-ssl:mysql-different-cn
      - sshproxy

  dev:
    <<: *app
    volumes:
      - .:/code
      - ./data:/data
      - ./docker/ssl/certificates:/ssl-cert
      - ssh-keys:/root/.ssh:ro

  mysql:
    image: mysql:${MYSQL_VERSION}
    command: mysqld --local-infile --port=3306 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: rootpassword

  mysql-ssl:
    image: mysql:${MYSQL_VERSION}
    command: mysqld --local-infile --port=3306 --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/ssl/certificates:/ssl-cert
      - ./docker/mysql-ssl/${MYSQL_VERSION}/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: rootpassword

  sshproxy:
    image: keboola/db-component-ssh-proxy:latest
    volumes:
      - ssh-keys:/root/.ssh
    links:
      - mysql

  wait:
    image: waisbrot/wait
    depends_on:
      - mysql
      - mysql-ssl
    environment:
      - TARGETS=mysql:3306,mysql-ssl:3306
      - TIMEOUT=200

volumes:
  ssh-keys:
