version: "3"
services:
  app5: &app5
    build: .
    image: keboola/ex-db-mysql
    command: composer ci
    environment:
      MYSQL_DB_HOST: mysql
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: rootpassword
      MYSQL_DB_DATABASE: test
      MYSQL_DB_PORT: 3306
    volumes:
      - ./tests/ssl-certs/mysql5:/ssl-cert
      - ssh-keys:/root/.ssh:ro
    links:
      - mysql5:mysql
      - mysql5:mysql-different-cn
      - sshproxy5:sshproxy

  app8: &app8
    build: .
    image: keboola/ex-db-mysql
    command: composer ci
    environment:
      MYSQL_DB_HOST: mysql
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: rootpassword
      MYSQL_DB_DATABASE: test
      MYSQL_DB_PORT: 3306
    volumes:
      - ./tests/ssl-certs/mysql8:/ssl-cert
      - ssh-keys:/root/.ssh:ro
    links:
      - mysql8:mysql
      - mysql8:mysql-different-cn
      - sshproxy8:sshproxy

  dev:
    <<: *app5
    volumes:
      - .:/code
      - ./data:/data
      - ./tests/ssl-certs/mysql5:/ssl-cert
      - ssh-keys:/root/.ssh:ro

  dev8:
    <<: *app8
    volumes:
      - .:/code
      - ./data:/data
      - ./tests/ssl-certs/mysql8:/ssl-cert
      - ssh-keys:/root/.ssh:ro

  mysql5:
    image: mysql:5.6
    volumes:
      - ./tests/ssl-certs/mysql5:/ssl-cert
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: rootpassword

  mysql8:
    image: mysql:8
    volumes:
      - ./tests/ssl-certs/mysql8:/ssl-cert
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: rootpassword
    command: mysqld --local-infile --port=3306 --default-authentication-plugin=mysql_native_password

  sshproxy5:
    image: keboola/db-component-ssh-proxy:latest
    volumes:
      - ssh-keys:/root/.ssh
    links:
      - mysql5:mysql

  sshproxy8:
    image: keboola/db-component-ssh-proxy:latest
    volumes:
      - ssh-keys:/root/.ssh
    links:
      - mysql8:mysql

  wait5:
    image: waisbrot/wait
    depends_on:
      - mysql5
    environment:
      - TARGETS=mysql5:3306
      - TIMEOUT=200

  wait8:
    image: waisbrot/wait
    depends_on:
      - mysql8
    environment:
      - TARGETS=mysql8:3306
      - TIMEOUT=200

volumes:
  ssh-keys:
