version: "2"
services:
  app:
    build: .
    image: keboola/ex-db-mysql
    command: composer ci
    tty: true
    stdin_open: true
    env_file:
      - ssh-keys.env
    environment:
      MYSQL_DB_HOST: mysql
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: rootpassword
      MYSQL_DB_DATABASE: test
      MYSQL_DB_PORT: 3306
      APP_NAME: ex-db-mysql
      ROOT_PATH: /code
    links:
      - mysql
      - mysql:mysql-different-cn
      - sshproxy

  dev:
    image: keboola/ex-db-mysql
    volumes:
      - .:/code
    command: composer ci
    tty: true
    stdin_open: true
    env_file:
      - ssh-keys.env
    environment:
      MYSQL_DB_HOST: mysql
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: rootpassword
      MYSQL_DB_DATABASE: test
      MYSQL_DB_PORT: 3306
      APP_NAME: ex-db-mysql
      ROOT_PATH: /code
    links:
      - mysql
      - mysql:mysql-different-cn
      - sshproxy

  mysql:
    image: mysql:5.6
    volumes:
        - ./tests/data/mysql/ssl:/ssl-cert
        - ./tests/data/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: rootpassword

  sshproxy:
    build: ./tests/env/sshproxy
    volumes:
        - ./tests/env/sshproxy:/code
    working_dir: /code
    ports:
      - "2222:22"
    links:
      - mysql
