version: "2"
services:
  app:
    build: .
    image: keboola/ex-db-mysql
    command: composer ci
    environment:
      MYSQL_DB_HOST: mysql
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: rootpassword
      MYSQL_DB_DATABASE: test
      MYSQL_DB_PORT: 3306
    volumes:
      - ./tests/data/mysql/ssl/mysql5:/ssl-cert
    links:
      - mysql
      - mysql:mysql-different-cn
      - sshproxy

  app8:
    build: .
    image: keboola/ex-db-mysql
    command: composer ci
    environment:
      MYSQL_DB_HOST: mysql
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: rootpassword
      MYSQL_DB_DATABASE: test
      MYSQL_DB_PORT: 3307
    volumes:
      - ./tests/data/mysql/ssl/mysql8:/ssl-cert
    links:
      - mysql8:mysql
      - mysql8:mysql-different-cn
      - sshproxy8:sshproxy

  dev:
    build:
      context: .
    image: keboola/ex-db-mysql
    volumes:
      - .:/code
    command: composer ci
    environment:
      MYSQL_DB_HOST: mysql
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: rootpassword
      MYSQL_DB_DATABASE: test
      MYSQL_DB_PORT: 3306
    links:
      - mysql
      - mysql:mysql-different-cn
      - sshproxy

  mysql:
    image: mysql:5.6
    volumes:
        - ./tests/data/mysql/ssl:/ssl-cert
        - ./tests/data/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: rootpassword

  mysql8:
    image: mysql:8
    volumes:
        - ./tests/data/mysql/ssl:/ssl-cert
        - ./tests/data/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: rootpassword
    command:
      - mysqld
      - --local-infile
      - --port=3307
      - --default-authentication-plugin=mysql_native_password
    expose:
      - "3307"

  sshproxy:
    image: keboola/db-component-ssh-proxy:latest
    ports:
      - "2222:22"
    links:
      - mysql

  sshproxy8:
    image: keboola/db-component-ssh-proxy:latest
    ports:
      - "2222:22"
    links:
      - mysql8:mysql
