<?php

declare(strict_types=1);

namespace Keboola\DbExtractor\Tests;

use PDO;

class TaintedPDOStatement extends \PDOStatement
{
    /**
     * @var callable
     */
    private $callback;

    /**
     * @var PDO
     */
    private $pdo;

    private function __construct(\PDO $pdo, $onEvent)
    {
        $this->pdo = $pdo;
        $this->callback = $onEvent;
    }

    public function fetch($fetch_style = null, $cursor_orientation = PDO::FETCH_ORI_NEXT, $cursor_offset = 0)
    {
        if ($fetch_style === null) {
            $fetch_style = PDO::FETCH_BOTH;
        }
        call_user_func($this->callback, 'fetch', $this, $this->pdo);
        //fwrite(STDERR, sprintf('[%s] Fetching', date('Y-m-d H:i:s')) . PHP_EOL);
        //fwrite(STDERR, 'fetching' . PHP_EOL);
        //exec('docker network disconnect db-extractor-common_db_network db_tests', $output, $ret);
        //exec('timeout 60 tcpkill -9 port 3360 2>&1');
        //if ($this->cnt === 0 || $this->cnt % 10000 === 0) {
          //  fwrite(STDERR, sprintf('[%s] Killing', date('Y-m-d H:i:s')) . PHP_EOL);
            //exec('php ' . __DIR__ . '/killerRabbit.php 0 > /dev/null &');
            //sleep(15);
        //}
        //$this->cnt++;
        return parent::fetch($fetch_style, $cursor_orientation, $cursor_offset); // TODO: Change the autogenerated stub
    }
}
