sudo: false

services:
  - docker

before_script:
  - docker-compose -v
  - docker-compose build
  - docker-compose run --rm app php ./tests/loadS3.php
  - docker-compose run --rm app composer ci
  - docker pull quay.io/keboola/developer-portal-cli-v2:latest
  - export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository keboola keboola.ex-db-redshift`
  - docker tag keboola/ex-db-redshift:latest $REPOSITORY:master
  - eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login keboola keboola.ex-db-redshift)
  - docker push $REPOSITORY:master
  - docker pull quay.io/keboola/syrup-cli:latest

script:
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-redshift 287551509 master
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-redshift 287589655 master
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-redshift 315245768 master

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true

notifications:
  email: false
  slack:
    secure: EWAdT2317Jqh/y/PjmlZggVe/zdMEupQ2EvVteZXoNM5eHqjXEIABezuIHghsDxCZYGY/2crrA3B73iha6gOqQzC8TzoqMlOrLfuotvIwu3MzG9ONaJVXM6DuVkWzl1Odp8gW7QmfMKs97jclDYTA1wUw47IvuWZOWvwo8j0eH0waKgHepnryaOcZ7p341Jj6fvZQqD/eatxofwdqeKRzeURMaorgb2+g+uzoheG7Nk+mbkNr028Kycr4V5QLPzSFrERbitaNHSELZzlrOP9v89+PIJ8rYwVNMCzVX+f53inMYt3xIOLrILN+lJip5KluTSjbwJweDwrZ9F8iTbMEt7XcPcASZ/0+VeiakVCQmZXNMEGuFRHc7rL3YmXEIbDDrqkDOeHh3vJjvAUYcpneCSD79ZsMoHrkbfGAsIL64fp5Mjp53rstayEXyLF9eG+FUUBPa9zJ5Ybu9alVXW3++pL1rY2C/sEXXSkh9QWpa7niUzKCqMQ6jRZzxqLTM/8O18ZBJzF/zksgXTpcI/8YDkCokqMQDLmeVrhHi772vRLc8eY9scGVKLuhwKcT9YigrehTUNqHYSO8jcQNR5bIHViI/HEflrXH2SAJyzfQT4VhDTw9JhpUcqY4ETsXR7ls8eLY6qcbhaM/3SHL4laf3z1QbYMm5prFBbT2ymwerA=
