version: "2"
services:
  app:
    build: .
    image: keboola/ex-db-redshift
    volumes:
        - .:/code
    working_dir: /code
    command: "./phpunit.sh"
    tty: true
    stdin_open: true
    environment:
      - REDSHIFT_DB_HOST
      - REDSHIFT_DB_PORT
      - REDSHIFT_DB_DATABASE
      - REDSHIFT_DB_USER
      - REDSHIFT_DB_PASSWORD
      - REDSHIFT_DB_SCHEMA
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - AWS_REGION
      - AWS_S3_BUCKET
    links:
      - sshproxy

  sshproxy:
    build: ./tests/env/sshproxy
    volumes:
        - ./tests/env/sshproxy:/code
    working_dir: /code
    ports:
      - "2222:22"

