version: '3.8'

services:
  mariadb:
    image: mariadb:${MARIADB_VERSION:-11.1}
    environment:
      MARIADB_DATABASE: testdb
      MARIADB_ROOT_PASSWORD: somePassword

  mysql:
    image: mysql:${MYSQL_VERSION:-5.6}
    command: mysqld --local-infile=1 --port=3306 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: somePassword

  mysql-ssl:
    image: mysql:${MYSQL_VERSION:-5.6}
    command: mysqld --local-infile=1 --port=3306 --default-authentication-plugin=mysql_native_password
    volumes:
      - ../docker/databases/mysql/conf.d/${MYSQL_VERSION:-5.6}:/etc/mysql/conf.d
      - ../docker/databases/mysql/ssl:/ssl-cert
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: somePassword

  mssql: &mssql
    image: mssql-server-linux
    build:
      context: ..
      target: mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "yourStrong(!)Password"

  mssql-ssl:
    <<: *mssql
    image: mssql-server-linux-ssl
    ports:
      - "1434:1433"
    build:
      context: ..
      target: mssql-ssl

  mssql-ssl-invalid-cn:
    <<: *mssql
    image: mssql-server-linux-ssl-invalid-cn
    ports:
      - "1435:1433"
    build:
      context: ..
      target: mssql-ssl-invalid-cn

  pgsql: &pgsql
    image: keboola/pgsql-test:${PGSQL_VERSION:-13}
    build:
      args:
        PGSQL_VERSION: ${PGSQL_VERSION:-13}
      context: ..
      target: pgsql
    volumes:
      - ../docker/databases/pgsql/init-sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=some password

  pgsql-ssl:
    <<: *pgsql
    image: keboola/pgsql-ssl-test:${PGSQL_VERSION:-13}
    command: -c hba_file=/etc/postgresql/pg_hba_ssl.conf -c ssl=on -c ssl_ca_file=/ssl-cert/ca-cert.pem -c ssl_cert_file=/ssl-cert/server-cert.pem -c ssl_key_file=/ssl-cert/server-key.pem
