version: '3.8'

services:
  mariadb:
    image: mariadb:${MARIADB_VERSION:-11.1}
    environment:
      MARIADB_DATABASE: testdb
      MARIADB_ROOT_PASSWORD: somePassword

  mysql:
    image: mysql:${MYSQL_VERSION:-5.6}
    command: mysqld --local-infile=1 --port=3306 --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: somePassword

  mysql-ssl:
    image: mysql:${MYSQL_VERSION:-5.6}
    command: mysqld --local-infile=1 --port=3306 --default-authentication-plugin=mysql_native_password
    volumes:
      - ../certs/mysql/conf.d/${MYSQL_VERSION:-5.6}:/etc/mysql/conf.d
      - ../certs/mysql/ssl:/ssl-cert
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: somePassword

  mssql: &mssql
    image: mssql-server-linux
    build:
      context: ..
      target: mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "yourStrong(!)Password"

  mssql-ssl:
    <<: *mssql
    image: mssql-server-linux-ssl
    ports:
      - "1434:1433"
    build:
      context: ..
      target: mssql-ssl

  mssql-ssl-invalid-cn:
    <<: *mssql
    image: mssql-server-linux-ssl-invalid-cn
    ports:
      - "1435:1433"
    build:
      context: ..
      target: mssql-ssl-invalid-cn