version: '3.8'

services:
  wait-mariadb:
    image: waisbrot/wait
    links:
      - mariadb
    environment:
      - TARGETS=mariadb:3306
      - TIMEOUT=120

  wait-mysql:
    image: waisbrot/wait
    links:
      - mysql
    environment:
      - TARGETS=mysql:3306
      - TIMEOUT=120

  wait-mysql-ssl:
    image: waisbrot/wait
    links:
      - mysql-ssl
    environment:
      - TARGETS=mysql-ssl:3306
      - TIMEOUT=120

  wait-mssql:
    image: waisbrot/wait
    links:
      - mssql
    environment:
      - TARGETS=mssql:1433
      - TIMEOUT=120

  wait-mssql-ssl:
    image: waisbrot/wait
    links:
      - mssql-ssl
    environment:
      - TARGETS=mssql-ssl:1433
      - TIMEOUT=120

  wait-mssql-ssl-invalid-cn:
    image: waisbrot/wait
    links:
      - mssql-ssl-invalid-cn
    environment:
      - TARGETS=mssql-ssl-invalid-cn:1433
      - TIMEOUT=120

  wait-pgsql:
    image: waisbrot/wait
    links:
      - pgsql
    environment:
      - TARGETS=pgsql:5432
      - TIMEOUT=120

  wait-pgsql-ssl:
    image: waisbrot/wait
    links:
      - pgsql-ssl
    environment:
      - TARGETS=pgsql-ssl:5432
      - TIMEOUT=120

  wait-sshproxy:
    image: waisbrot/wait
    links:
      - sshproxy
    environment:
      - TARGETS=sshproxy:22
      - TIMEOUT=120

  sshproxy:
    image: keboola/db-component-ssh-proxy:latest
    volumes:
      - ssh-keys:/root/.ssh

  toxiproxy:
    image: shopify/toxiproxy
