sudo: required
language: bash
services:
- docker
install:
- docker-compose build
- docker-compose run --rm wait
- docker-compose run --rm app composer ci
script:
- docker pull quay.io/keboola/developer-portal-cli-v2:latest
- export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD
  quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR
  $KBC_DEVELOPERPORTAL_APP`
- docker tag $KBC_APP_REPOSITORY:latest $REPOSITORY:master
- eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD
  quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR
  $KBC_DEVELOPERPORTAL_APP)
- docker push $REPOSITORY:master
- docker pull quay.io/keboola/syrup-cli:latest
- docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP
  287646782 master
- docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP
  287674685 master
- docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP
  419388902 master
after_success:
- docker images
after_error:
- docker-compose logs
after_failure:
- docker-compose logs
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true
notifications:
  slack:
    secure: T6H2vqIJcHvklnlUMAr8rJ26N7fx8zW5Tce9JlSgWx6h2A5odDgs16NEQVYjoG7t9lJh2IWdVKRabm7jXy5NFjUPQt84uPHOo0HdfbwKjqIbgjOGLpS9AXXgPo4jJRQO40/1StM6B7snDKOgm8StgQStuUe6b9eyMahWN2F8pet74RvdVAd0jfsoQPwYcw9pDdTQnZM//9G9JrHDpUUuk9+K3BxlJgB3Gh6u78hyfnY81JMDZzn1QkBOuZUpbirxnenUYmeBUE3Nh1TD/jTx90rghwbdsQ5gzrvulSXr+6xfiqb/eRukn86IQlb9GxbIcgwd6YwBdM+hslIKJhWT8LYqgljRcIE2oeZoAaKdgIZp/L9capodZqm+QxTRy1dz5wSdloAjHPAjgXR3HRb3dYcrxbqAikydoMuWolybwDU1+W+bqnLP/5bMjz+oBGN/wphtL43ZERMBBNrmda51ZICZoQPu6w4+yH37h+qqQ3qhG4fJf1UO682hornVsS3fOT0AWNtO/MS7t0ZobbIkYG7kPgOVf5rRbqZApdWQmQnQCrKSYVJtIRcr8Rj4hdmWMr0BWs4fH8zZx4tg6RvZfkhy9qya9U4meiLY1GP0QHKQBVveoQwX/s4zETIVjIVpmzH0J0ceDjteMgTfT4vZNp5pjP3Ie5DLnmqrufXrSp0=
