sudo: required

language: bash

services:
  - docker

before_install:
  - docker-compose -v

install:
  - docker-compose build
  - docker-compose run --rm app composer ci

script:
  - docker pull quay.io/keboola/developer-portal-cli-v2:latest
  - export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD
    quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository
    keboola keboola.ex-db-snowflake`
  - docker tag keboola/ex-db-snowflake:latest $REPOSITORY:master
  - eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD
    quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login
    keboola keboola.ex-db-snowflake)
  - docker push $REPOSITORY:master
  - docker pull quay.io/keboola/syrup-cli:latest
  - docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-snowflake
    288409174 master

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true
