version: '2'
services:
  app:
    build: .
    image: keboola/ex-db-snowflake
    working_dir: /code
    command: "./phpunit.sh"
    tty: true
    stdin_open: true
    environment:
      - STORAGE_API_TOKEN
      - SNOWFLAKE_DB_HOST
      - SNOWFLAKE_DB_PORT
      - SNOWFLAKE_DB_USER
      - SNOWFLAKE_DB_PASSWORD
      - SNOWFLAKE_DB_DATABASE
      - SNOWFLAKE_DB_SCHEMA
      - SNOWFLAKE_DB_WAREHOUSE

  drivers-download:
      build:
        context: .
        dockerfile: ./driver/Dockerfile
      working_dir: /code
      volumes:
        - .:/code
      environment:
        - AWS_ACCESS_KEY
        - AWS_SECRET_KEY
        - AWS_S3_BUCKET
        - AWS_REGION

