version: '2'
services:
  app: &base
    build:
      context: .
    image: keboola/ex-db-snowflake
    environment:
      - KBC_RUNID
      - STORAGE_API_TOKEN
      - SNOWFLAKE_DB_HOST
      - SNOWFLAKE_DB_PORT
      - SNOWFLAKE_DB_USER
      - SNOWFLAKE_DB_PASSWORD
      - SNOWFLAKE_DB_DATABASE
      - SNOWFLAKE_DB_SCHEMA
      - SNOWFLAKE_DB_WAREHOUSE
  dev:
    <<: *base
    volumes:
      - .:/code
      - ./data:/data
