name: GitHub Actions
on: [push]
env:
  APP_IMAGE: keboola/db-extractor-redshift
  AWS_ACCESS_KEY: "AKIAQ4QRYXTAFFHFZRFP"
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_REGION: "us-east-1"
  AWS_S3_BUCKET: "ex-db-redshift-tests-s3filesbucket-1ps6rluceepbd"
  KBC_DEVELOPERPORTAL_VENDOR: "keboola"
  KBC_DEVELOPERPORTAL_APP: "keboola.ex-db-redshift"
  KBC_DEVELOPERPORTAL_USERNAME: "keboola+github_actions_db_extractor_redshift"
  KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
  KBC_TEST_PROJECT_URL: "https://connection.keboola.com/admin/projects/2703/dashboard"
  KBC_STORAGE_TOKEN: ${{ secrets.KBC_STORAGE_TOKEN }}
  REDSHIFT_DB_HOST: "testing.cx4py8yq28xb.us-east-1.redshift.amazonaws.com"
  REDSHIFT_DB_PORT: "5439"
  REDSHIFT_DB_USER: "gh_actions_db_ex_tests"
  REDSHIFT_DB_PASSWORD: ${{ secrets.REDSHIFT_DB_PASSWORD }}
  REDSHIFT_DB_DATABASE: "gh_actions_db_ex_tests"
  DOCKERHUB_USER: "keboolabot"
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Print Docker version
        run: |
          docker -v
      - name: Build image and run tests
        run: |
          docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"
          docker build -t $APP_IMAGE .
          docker-compose run --rm app composer ci
      - name: Push image to ECR
        run: |
          docker pull quay.io/keboola/developer-portal-cli-v2:latest
          export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
          docker tag $APP_IMAGE:latest $REPOSITORY:test
          eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
          docker push $REPOSITORY:test
          docker pull quay.io/keboola/syrup-cli:latest
      - name: Run KBC test jobs
        run: |
          docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-redshift 287551509 master
          docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-redshift 287589655 master
          docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job keboola.ex-db-redshift 315245768 master
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/')
        run: ./deploy.sh
