app:
  build: .
  volumes:
      - .:/code
  working_dir: /code
  entrypoint: "./phpunit.sh"
  tty: true
  stdin_open: true
  environment:
    - PGSQL_DB_HOST=pgsql
    - PGSQL_DB_PORT=5432
    - PGSQL_DB_DATABASE=postgres
    - PGSQL_DB_USER=postgres
    - PGSQL_DB_PASSWORD=some password
  links:
    - pgsql

pgsql:
  image: postgres
  environment:
    - PGSQL_DB_HOST=pgsql
    - PGSQL_DB_PORT=5432
    - PGSQL_DB_DATABASE=postgres
    - PGSQL_DB_USER=postgres
    - PGSQL_DB_PASSWORD=some password
