version: "2"
services:
  app:
    build: .
    image: keboola/db-extractor-pgsql
    tty: true
    stdin_open: true
    volumes:
      - .:/code
    command: ./phpunit.sh
    environment:
      - PGSQL_DB_HOST=pgsql
      - PGSQL_DB_PORT=5432
      - PGSQL_DB_DATABASE=postgres
      - PGSQL_DB_USER=postgres
      - PGSQL_DB_PASSWORD=some password
      - PGPASSWORD=some password
    links:
      - pgsql
      - sshproxy

  pgsql:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=some password

  sshproxy:
    build: ./tests/env/sshproxy
    volumes:
        - ./tests/env/sshproxy:/code
    working_dir: /code
    ports:
      - "2222:22"
    links:
      - pgsql
