version: "2"
services:
  app:
    build: .
    image: keboola/db-extractor-pgsql
    working_dir: /code
    tty: true
    stdin_open: true
    volumes:
      - ./:/code
    command: "./phpunit.sh"
    environment:
      - EXTERNAL_PG_HOST
      - EXTERNAL_PG_PORT
      - EXTERNAL_PG_DATABASE
      - EXTERNAL_PG_USER
      - EXTERNAL_PG_PASSWORD
      - PGSQL_DB_HOST
      - PGSQL_DB_PORT
      - PGSQL_DB_DATABASE
      - PGSQL_DB_USER
      - PGSQL_DB_PASSWORD
    links:
      - pgsql
      - sshproxy

  pgsql:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=some password

  sshproxy:
    build: ./tests/env/sshproxy
    volumes:
        - ./tests/env/sshproxy:/code
    working_dir: /code
    ports:
      - "2222:22"
    links:
      - pgsql
